#!/bin/bash
LOGS="/opt/logs/ADA.log.`date +%d-%b-%Y`"
ADA trade --paper \
binance.ADA-BTC  \
--min_prev_trades=10 \
--use_prev_trades \
--strategy=ta_macd_ext \
--period=2m \
--min_periods=52 \
--ema_short_period=12 \
--ema_long_period=26 \
--signal_period=9 \
--fast_ma_type=EMA \
--slow_ma_type=EMA \
--signal_ma_type=EMA \
--default_ma_type=signal_ma_type \
--up_trend_threshold=0 \
--down_trend_threshold=0 \
--overbought_rsi_periods=25 \
--overbought_rsi=82 \
--poll_trades=3000 \
--order_poll_time=5000 \
--exact_buy_orders \
--exact_sell_orders \
--order_adjust_time=5000 \
--sell_stop_pct=0 \
--buy_stop_pct=0 \
--max_sell_loss_pct=2 \
--max_buy_loss_pct=100 \
--profit_stop_enable_pct=3 \
--max_slippage_pct=25 \
--profit_stop_pct=0.1 \
--markdown_buy_pct=0.23 \
--markup_sell_pct=0.24 --sell_pct=100 --buy_pct=100  2>&1 | tee $LOGS
# 18 24
# 19 19
## 16 26
