#!/bin/bash
LOGS="/opt/logs/BNB.log.`date +%d-%b-%Y`"
BNB trade \
binance.BNB-BTC  \
--min_prev_trades=10 \
--use_prev_trades \
--strategy=ta_macd \
--period=2m \
--min_periods=52 \
--ema_short_period=12 \
--ema_long_period=26 \
--signal_period=9 \
--up_trend_threshold=0 \
--down_trend_threshold=0 \
--overbought_rsi_periods=30 \
--overbought_rsi=70 \
--poll_trades=2000 \
--order_poll_time=5000 \
--exact_buy_orders \
--exact_sell_orders \
--order_adjust_time=5000 \
--sell_stop_pct=0 \
--buy_stop_pct=0 \
--max_sell_loss_pct=1 \
--max_buy_loss_pct=100 \
--profit_stop_enable_pct=4 \
--max_slippage_pct=2 \
--profit_stop_pct=0 \
--markdown_buy_pct=0.16 \
--markup_sell_pct=0.15 --sell_pct=100 --buy_pct=100  2>&1 | tee $LOGS
# 27 27 
# 21 20
