#!/bin/bash
LOGS="/opt/logs/BTC.log.`date +%d-%b-%Y`"
BTC trade \
binance.BTC-USDT \
--min_prev_trades=0 \
--use_prev_trades \
--quarentine_time=15 \
--strategy=multi \
--period_length=3m \
--order_adjust_time=11000 \
--order_poll_time=11000 \
--min_periods=52 \
--overbought_rsi_periods=25 \
--overbought_rsi=74 \
--length=8 \
--fish_pct_change=0 \
--pos_length=2 \
--src=ohlc4 \
--momentum_size=9 \
--max_sell_loss_pct=25 \
--profit_stop_enable_pct=4 \
--profit_stop_pct=1 \
--exact_buy_orders \
--exact_sell_orders \
--max_buy_loss_pct=99 \
--max_slippage_pct=4 \
--markdown_buy_pct=0.25 \
--markup_sell_pct=0.20 \
--sell_pct=100 --buy_pct=100 2>&1 | tee $LOGS
#--use_prev_trades \
#--min_prev_trades=0 \
# 27 60
#24 54
#--poll_trades=1000 \
#--min_prev_trades=10 \
#--use_prev_trades \
#--markdown_buy_pct=0.67 \
#--markup_sell_pct=0.57 \
#--poll_trades=4000 \
