#!/bin/bash
LOGS="/opt/logs/BTT.log.`date +%d-%b-%Y`"
BTT trade \
binance.BTT-BTC  \
--min_prev_trades=10 \
--use_prev_trades \
--strategy=ta_macd_ext \
--period=1h \
--min_periods=52 \
--poll_trades=3000 \
--order_poll_time=5000 \
--exact_buy_orders \
--exact_sell_orders \
--order_adjust_time=5000 \
--max_sell_loss_pct=25 \
--profit_stop_enable_pct=0 \
--profit_stop_pct=0 \
--markdown_buy_pct=0 \
--markup_sell_pct=0 --sell_pct=100 --buy_pct=100  2>&1 | tee $LOGS
#25 24
