#!/bin/bash
LOGS="/opt/logs/BTT.log.`date +%d-%b-%Y`"
BTT trade \
binance.BTT-BTC  \
--min_prev_trades=10 \
--use_prev_trades \
--strategy=multi \
--period_length=1m \
--min_periods=52 \
--overbought_rsi_periods=25 \
--overbought_rsi=74 \
--length=11 \
--fish_pct_change=0 \
--pos_length=2 \
--src=ohlc4 \
--momentum_size=7 \
--max_sell_loss_pct=0 \
--profit_stop_enable_pct=0 \
--profit_stop_pct=0 \
--exact_buy_orders \
--exact_sell_orders \
--max_slippage_pct=4 \
--markdown_buy_pct=0 \
--markup_sell_pct=0 \
--sell_pct=100 --buy_pct=100  2>&1 | tee $LOGS
#25 24
