#!/bin/bash
LOGS="/opt/logs/DLT.log.`date +%d-%b-%Y`"
DLT trade \
binance.DLT-BTC \
--min_prev_trades=1 \
--use_prev_trades \
--strategy=multi \
--period_length=3m \
--order_adjust_time=14000 \
--order_poll_time=14000 \
--poll_trades=5000 \
--min_periods=52 \
--overbought_rsi_periods=25 \
--overbought_rsi=74 \
--length=8 \
--fish_pct_change=0 \
--pos_length=2 \
--src=ohlc4 \
--momentum_size=9 \
--max_sell_loss_pct=5 \
--profit_stop_enable_pct=5 \
--profit_stop_pct=1 \
--exact_buy_orders \
--exact_sell_orders \
--max_slippage_pct=4 \
--markdown_buy_pct=0.45 \
--markup_sell_pct=0.40 \
--sell_pct=100 --buy_pct=100 2>&1 | tee $LOGS
#--poll_trades=11000 \
# order_adjust_time=14000 

#--order_adjust_time=16000  \
#--order_poll_time=16000  \
