#!/bin/bash
LOGS="/opt/logs/EOS.log.`date +%d-%b-%Y`"
EOS trade \
binance.EOS-BTC  \
--deposit=0.02 \
--buy_max_amt=0.02 \
--min_prev_trades=1 \
--use_fee_asset \
--use_prev_trades \
--strategy=macd \
--period=2m \
--min_periods=52 \
--ema_short_period=12 \
--ema_long_period=26 \
--signal_period=5 \
--up_trend_threshold=0 \
--down_trend_threshold=0 \
--overbought_rsi_periods=25 \
--overbought_rsi=71 \
--poll_trades=3000 \
--exact_buy_orders \
--exact_sell_orders \
--order_adjust_time=5000 \
--sell_stop_pct=0 \
--buy_stop_pct=0 \
--max_sell_loss_pct=1 \
--max_buy_loss_pct=100 \
--profit_stop_enable_pct=4 \
--max_slippage_pct=1 \
--profit_stop_pct=0.6  \
--markdown_buy_pct=0.13 \
--markup_sell_pct=0.14 --sell_pct=100 --buy_pct=100  2>&1 | tee $LOGS
