#!/bin/bash
LOGS="/opt/logs/IIOTXX.log.`date +%d-%b-%Y`"
IIOTXX trade \
binance.IOTX-BTC \
--strategy=multi \
--period_length=3m \
--order_adjust_time=28000  \
--order_poll_time=28000  \
--poll_trades=28000 \
--min_periods=52 \
--overbought_rsi_periods=25 \
--overbought_rsi=74 \
--length=8 \
--fish_pct_change=0 \
--pos_length=2 \
--src=ohlc4 \
--momentum_size=9 \
--max_sell_loss_pct=6 \
--profit_stop_enable_pct=2 \
--profit_stop_pct=1 \
--exact_buy_orders \
--exact_sell_orders \
--max_slippage_pct=4 \
--markdown_buy_pct=0.70 \
--markup_sell_pct=0.66 \
--sell_pct=100 --buy_pct=100 2>&1 | tee $LOGS
#--markdown_buy_pct=0.45 \
#--markup_sell_pct=0.40 \
