#!/bin/bash
LOGS="/opt/logs/LTC.log.`date +%d-%b-%Y`"
LTC trade \
binance.LTC-BTC  \
--strategy=macd \
--min_prev_trades=1 \
--deposit=0.03 \
--exact_buy_orders \
--exact_sell_orders \
--use_prev_trades \
--period=2m \
--min_periods=52 \
--ema_short_period=12 \
--ema_long_period=26 \
--signal_period=9 \
--up_trend_threshold=0 \
--down_trend_threshold=0 \
--overbought_rsi_periods=20 \
--overbought_rsi=76 \
--poll_trades=3000 \
--sell_stop_pct=0 \
--buy_stop_pct=0 \
--order_poll_time=5000 \
--order_adjust_time=5000 \
--max_sell_loss_pct=2 \
--max_buy_loss_pct=100 \
--profit_stop_enable_pct=2 \
--profit_stop_pct=0.5 \
--markdown_buy_pct=0.23 \
--markup_sell_pct=0.23 --currency_capital=0.06 --sell_pct=100 --buy_pct=100 2>&1 | tee $LOGS
#--currency_capital=0.06 --sell_pct=100 --buy_pct=100  --days=7 \ --use_prev_trades
#54 49
