#!/bin/bash
LOGS="/opt/logs/PHX.log.`date +%d-%b-%Y`"
PHX trade \
binance.PHX-BTC  \
--strategy=multi \
--period_length=3m \
--order_adjust_time=2000 \
--order_poll_time=2000 \
--poll_trades=1000 \
--min_periods=52 \
--overbought_rsi_periods=25 \
--overbought_rsi=74 \
--length=10 \
--fish_pct_change=0 \
--pos_length=1 \
--src=ohlc4 \
--momentum_size=5 \
--max_sell_loss_pct=7 \
--profit_stop_enable_pct=9 \
--profit_stop_pct=0 \
--max_slippage_pct=5 \
--exact_sell_orders \
--exact_buy_orders \
--markdown_buy_pct=0 \
--markup_sell_pct=0 \
--sell_pct=100 --buy_pct=100 2>&1 | tee $LOGS
# 56 64
