#!/bin/bash
LOGS="/opt/logs/QKC.log.`date +%d-%b-%Y`"
QKC trade \
binance.QKC-BTC \
--min_prev_trades=10 \
--use_prev_trades \
--strategy=multi \
--period_length=3m \
--order_adjust_time=2000 \
--order_poll_time=1000 \
--poll_trades=5000 \
--min_periods=52 \
--overbought_rsi_periods=25 \
--overbought_rsi=74 \
--length=11 \
--fish_pct_change=0.5 \
--pos_length=2 \
--src=ohlc4 \
--momentum_size=7 \
--max_sell_loss_pct=6 \
--profit_stop_enable_pct=4 \
--profit_stop_pct=1 \
--exact_buy_orders \
--exact_sell_orders \
--max_slippage_pct=4 \
--markdown_buy_pct=0.20 \
--markup_sell_pct=0.66 \
--sell_pct=100 --buy_pct=100 2>&1 | tee $LOGS
