#!/bin/bash
LOGS="/opt/logs/RRVNN2.log.`date +%d-%b-%Y`"
RRVNN2 trade \
binance.RVN-BTC  \
--strategy=multi \
--quarentine_time=5 \
--period_length=3m \
--poll_trades=4000 \
--order_adjust_time=4000 \
--order_poll_time=5000 \
--min_periods=52 \
--overbought_rsi_periods=25 \
--overbought_rsi=74 \
--length=11 \
--fish_pct_change=0 \
--pos_length=2 \
--src=ohlc4 \
--momentum_size=7 \
--max_sell_loss_pct=3 \
--profit_stop_enable_pct=3 \
--profit_stop_pct=1 \
--exact_buy_orders \
--exact_sell_orders \
--max_slippage_pct=4 \
--markdown_buy_pct=0.26 \
--markup_sell_pct=0.53 \
--min_prev_trades=10 \
--use_prev_trades \
--sell_pct=100 --buy_pct=100 2>&1 | tee $LOGS
#24 54

#--min_prev_trades=10 \

#--use_prev_trades \

#--markdown_buy_pct=0.67 \

#--markup_sell_pct=0.57 \

#--poll_trades=4000 \

