#!/bin/bash
LOGS="/opt/logs/RVN.log.`date +%d-%b-%Y`"
RVN trade \
binance.RVN-BTC \
--min_prev_trades=10 \
--use_prev_trades \
--period_length=3m \
--order_adjust_time=12000 \
--order_poll_time=12000 \
--poll_trades=10000 \
--min_periods=52 \
--overbought_rsi_periods=25 \
--overbought_rsi=74 \
--length=9 \
--fish_pct_change=0 \
--pos_length=2 \
--src=ohlc4 \
--momentum_size=10 \
--max_sell_loss_pct=4 \
--profit_stop_enable_pct=4 \
--profit_stop_pct=1 \
--exact_buy_orders \
--exact_sell_orders \
--max_slippage_pct=4 \
--markdown_buy_pct=0.29 \
--markup_sell_pct=0.19 \
--sell_pct=100 --buy_pct=100 2>&1 | tee $LOGS

#--markdown_buy_pct=0.20 \
#--markup_sell_pct=0.66 \

#--min_prev_trades=10 \
#--use_prev_trades \
#--markdown_buy_pct=0.67 \
#--markup_sell_pct=0.57 \
#--poll_trades=4000 \
