#!/bin/bash
LOGS="/opt/logs/XVG.log.`date +%d-%b-%Y`"
XVG trade \
binance.XVG-BTC  \
--strategy=macd \
--min_prev_trades=1 \
--use_fee_asset \
--deposit=0.02 \
--buy_max_amt=0.02 \
--period=2m \
--min_periods=52 \
--ema_short_period=12 \
--ema_long_period=26 \
--signal_period=2 \
--up_trend_threshold=0 \
--down_trend_threshold=0 \
--overbought_rsi_periods=20 \
--overbought_rsi=70 \
--poll_trades=5000 \
--exact_buy_orders \
--exact_sell_orders \
--order_adjust_time=5000 \
--sell_stop_pct=9 \
--buy_stop_pct=1 \
--max_sell_loss_pct=9 \
--max_buy_loss_pct=100 \
--profit_stop_enable_pct=1 \
--max_slippage_pct=1 \
--profit_stop_pct=0.4  \
--markdown_buy_pct=0.22 \
--markup_sell_pct=0.22 --sell_pct=100 --buy_pct=100  2>&1 | tee $LOGS
#--currency_capital=0.06 --sell_pct=100 --buy_pct=100  --days=7 \ --use_prev_trades
#54 49
