#!/bin/bash
LOGS="/opt/logs/XLM.log.`date +%d-%b-%Y`"
XLM trade \
binance.XLM-BTC  \
--strategy=macd \
--min_prev_trades=10 \
--use_prev_trades \
--period=2m \
--min_periods=52 \
--ema_short_period=12 \
--ema_long_period=26 \
--signal_period=9 \
--up_trend_threshold=0 \
--down_trend_threshold=0 \
--overbought_rsi_periods=28 \
--overbought_rsi=69 \
--poll_trades=5000 \
--exact_buy_orders \
--exact_sell_orders \
--order_adjust_time=5000 \
--sell_stop_pct=0 \
--buy_stop_pct=0 \
--max_sell_loss_pct=5 \
--max_buy_loss_pct=100 \
--profit_stop_enable_pct=5 \
--max_slippage_pct=1 \
--profit_stop_pct=0  \
--markdown_buy_pct=0.21 \
--markup_sell_pct=0.18 --sell_pct=100 --buy_pct=100 2>&1 | tee $LOGS
#18 19--deposit=0.04 --sell_pct=100 --buy_pct=100 \
