#!/bin/bash
LOGS="/opt/logs/XRB.log.`date +%d-%b-%Y`"
XRB trade \
binance.XRB-BTC  \
--deposit=0.007 \
--min_prev_trades=1 \
--use_prev_trades \
--strategy=macd \
--period=2m \
--min_periods=52 \
--ema_short_period=12 \
--ema_long_period=26 \
--signal_period=6 \
--up_trend_threshold=0 \
--down_trend_threshold=0 \
--overbought_rsi_periods=23 \
--overbought_rsi=78 \
--poll_trades=3000 \
--exact_buy_orders \
--exact_sell_orders \
--sell_stop_pct=4 \
--buy_stop_pct=4 \
--max_sell_loss_pct=2 \
--max_buy_loss_pct=100 \
--profit_stop_enable_pct=5 \
--profit_stop_pct=0.5 \
--markdown_buy_pct=0.79 \
--order_poll_time=5000 \
--order_adjust_time=5000 \
--markup_sell_pct=0.64 --sell_pct=100 --buy_pct=100 2>&1 | tee $LOGS
#37
